### ISSUE TITLE
newer IGV versions (including 2.7.x) cannot deal with asterisk in URLs

### ISSUE THREAD

**Issue by juleskers** [eilslabs/igv-crawler#3]
Upon testing IGV 2.7.0, we noticed that it could no longer open files that it handled in 2.4.16.
All the files that had problems had an asterisk (*) in the filename.
These same files *can* be opened via the "file > open" dialog, but also not via "file > open from URI" (same error); 

```
# igv.log, version 2.4.4:
INFO [2020-02-03 14:43:20,643]  [TrackLoader.java:126] [pool-2-thread-2]  Loading resource, path https://server.example.de/path/to/file_with_*_in_name.bam
INFO [2020-02-03 14:43:29,039]  [HttpUtils.java:864] [pool-2-thread-2]  Range-byte request succeeded
```

```
# igv.log, version 2.7.0
INFO [2020-02-03T14:46:43,294]  [TrackLoader.java:126] [pool-3-thread-4]  Loading resource, path https://server.example.de/path/to/file_with_*_in_name.bam
ERROR [2020-02-03T14:46:57,431]  [AlignmentTileLoader.java:315] [pool-2-thread-1]  Error loading alignment data
htsjdk.samtools.util.RuntimeIOException: Invalid file header in BAM index https://server.example.de/path/to/file_with_*_in_name.bam: 
	at htsjdk.samtools.AbstractBAMFileIndex.verifyIndexMagicNumber(AbstractBAMFileIndex.java:378) ~[htsjdk-2.20.3-2-ge357c42-SNAPSHOT.jar:?]
	at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:70) ~[htsjdk-2.20.3-2-ge357c42-SNAPSHOT.jar:?]
	at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:56) ~[htsjdk-2.20.3-2-ge357c42-SNAPSHOT.jar:?]
	at htsjdk.samtools.DiskBasedBAMFileIndex.<init>(DiskBasedBAMFileIndex.java:42) ~[htsjdk-2.20.3-2-ge357c42-SNAPSHOT.jar:?]
	at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:416) ~[htsjdk-2.20.3-2-ge357c42-SNAPSHOT.jar:?]
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:952) ~[htsjdk-2.20.3-2-ge357c42-SNAPSHOT.jar:?]
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:612) ~[htsjdk-2.20.3-2-ge357c42-SNAPSHOT.jar:?]
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533) ~[htsjdk-2.20.3-2-ge357c42-SNAPSHOT.jar:?]
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538) ~[htsjdk-2.20.3-2-ge357c42-SNAPSHOT.jar:?]
	at org.broad.igv.sam.reader.BAMReader.query(BAMReader.java:182) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentTileLoader.loadTile(AlignmentTileLoader.java:162) [igv.jar:?]
	at org.broad.igv.sam.AlignmentDataManager.loadInterval(AlignmentDataManager.java:410) [igv.jar:?]
	at org.broad.igv.sam.AlignmentDataManager.load(AlignmentDataManager.java:355) [igv.jar:?]
	at org.broad.igv.sam.AlignmentTrack.load(AlignmentTrack.java:418) [igv.jar:?]
	at org.broad.igv.ui.panel.DataPanel.lambda$load$3(DataPanel.java:225) [igv.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
INFO [2020-02-03T14:46:57,442]  [MessageUtils.java:76] [pool-2-thread-1]  <html>Error encountered querying alignments: htsjdk.samtools.util.RuntimeIOException: Invalid file header in BAM index https://server.example.de/path/to/file_with_*_in_name.bam: 
```

**Comment by juleskers** [comment]
'Fixed' in 3186968bbfde51bc1884c4b5d955af25d349384b, by replacing asterisk with a unicode look-a-like in the URLs+Symlinks we generate.
